### Send POST request with json body
POST https://code-challenge-nttdata-04.carloshuichi.workers.dev/earthquakes
Content-Type: application/json

{
  "intensity": 8.2,
  "deepness": 30.0,
  "geo": {
    "latitude": -33.4500,
    "longitude": -70.6700
  }
}

### GET request with parameter
GET https://code-challenge-nttdata-04.carloshuichi.workers.dev/earthquakes?latitude=-33.4489&longitude=-70.6693&radius=10&date=2025-10-05
Accept: application/json