### Send POST request with json body
POST http://localhost:8080/earthquakes
Content-Type: application/json

{
  "intensity": 3.1,
  "deepness": 5.2,
  "geo": {
    "latitude": -33.4478,
    "longitude": -70.6686
  }
}

### GET request with parameter
GET http://localhost:8080/earthquakes?latitude=-33.4489&longitude=-70.6693&radius=10&date=10-04-2025
Accept: application/json